// The files the two build paths emit into dist/. The real build compiles
// the wasm module and the placeholder build stands in for it where no Rust
// toolchain exists, but both ship the same JavaScript runtime and the same
// declarations. Held here once: when the lists lived in both scripts they
// drifted on a rename, and only the placeholder path failed.

/** Runtime modules copied verbatim from src/ into dist/. */
export const runtimeModules = [
  'core-wasm-error-runtime.js',
  'pinned-font-policy-runtime.js',
  'core-wasm-document-runtime.js',
  'core-wasm-versioned-runtime.js',
  'core-wasm-versioned-mutation-runtime.js',
  'core-wasm-versioned-validation-runtime.js',
  'chapter-local-owner-validation-runtime.js',
  'chapter-local-creation-validation-runtime.js',
  'chapter-local-frame-validation-runtime.js',
  'chapter-local-document-runtime.js',
  'revision-presentation-validation-runtime.js',
  'required-font-faces-validation-runtime.js',
  'reader-navigation-runtime.js',
  'reader-revision-session-runtime.js',
  'reader-revision-session-support-runtime.js',
  'reader-worker-cache-runtime.js',
  'reader-worker-client-runtime.js',
  'reader-worker-pinned-font-runtime.js',
  'reader-worker-interaction-validation-runtime.js',
  'reader-worker-page-target-validation-runtime.js',
  'reader-worker-page-semantics-validation-runtime.js',
  'reader-worker-page-semantics-runtime.js',
  'reader-worker-page-reading-anchor-validation-runtime.js',
  'reader-worker-page-reading-anchor-runtime.js',
  'reader-worker-exact-text-interaction-validation-runtime.js',
  'reader-worker-exact-text-range-validation-runtime.js',
  'reader-worker-text-source-span-validation-runtime.js',
  'reader-worker-text-range-from-points-validation-runtime.js',
  'reader-worker-text-selection-movement-validation-runtime.js',
  'reader-worker-annotation-validation-runtime.js',
  'reader-worker-exact-source-range-validation-runtime.js',
  'reader-worker-text-geometry-validation-runtime.js',
  'reader-worker-versioned-read-validation-runtime.js',
  'reader-worker-session-runtime.js',
  'reader-worker-versioned-client-runtime.js',
  'reader-worker-versioned-payload-runtime.js',
  'reader-worker-chapter-local-client-runtime.js',
  'reader-worker-chapter-local-payload-runtime.js',
  'frame-command-buffer-decoder-runtime.js',
  'reader-session-wire-base-runtime.js',
  'reader-session-display-paint-runtime.js',
  'reader-session-display-decoder-runtime.js',
  'reader-session-primitive-decoder-runtime.js',
  'reader-session-artifact-decoder-runtime.js',
  'reader-session-publication-runtime.js',
  'reader-session-request-runtime.js',
  'reader-session-foreground-runtime.js',
  'reader-session-background-runtime.js',
  'reader-session-query-request-runtime.js',
  'reader-session-query-decoder-runtime.js',
  'reader-session-worker-query-runtime.js',
  'reader-session-worker-runtime.js',
  'reader-session-worker-client-query-runtime.js',
  'reader-session-worker-client-runtime.js',
];

/** Hand-written declaration files whose contents are inlined into the bundle. */
export const decoderDeclarationFiles = [
  'frame-command-buffer-decoder-runtime.d.ts',
  'reader-session-runtime.d.ts',
];

/** Type modules under src/types/, named without their extension. */
export const typeModules = [
  'common',
  'frame-command',
  'publication',
  'revision',
  'chapter-local',
  'frame',
  'resource',
  'search',
  'reader-revision-session',
  'reader-worker',
  'reader-worker-versioned',
  'navigation',
  'page',
  'interaction-source',
  'interaction-text',
  'interaction-movement',
  'interaction-annotation',
  'reading-anchor',
  'status',
  'pinned-font',
  'reader-session-display',
  'reader-session-primitive',
  'reader-session',
  'reader-session-query',
  'reader-session-worker',
];
