export { buildHitMap, hitTest, resolveCharPosition, buildLinkMap, hitTestLink } from './core';
export { buildSemanticTree } from './core';
export type { HitEntry, HitMap, LinkRegion, TextPosition, TextRange } from './core';
export type { SemanticNode, SemanticRole } from './core';
export { getSelectionRects, getSelectedText, createSelectionEngine } from './selection';
export type { SelectionEngine, SelectionState, PointerInput } from './selection';
export { buildSearchIndex, search, createSearchEngine } from './search';
export type { SearchIndex, SearchResult, SearchOptions, SearchEngine } from './search';
export { resolveAnnotationRects } from './annotations';
export type { Annotation, AnnotationRenderData } from './annotations';
export { createReadingPosition, resolveReadingPosition, createPositionTracker } from './position';
export type { ReadingPosition, PositionTracker } from './position';
