export { DEFAULT_STYLE, inheritableStyle } from './defaults';
export { getTagStyle } from './tag-styles';
export {
  type BorderSide,
  BOX_SIZING_VALUES,
  type BoxSizing,
  type ComputedStyle,
  type CssRule,
  DISPLAY_VALUES,
  type Display,
  type FontFaceRule,
  FONT_STYLES,
  type FontStyle,
  FONT_WEIGHTS,
  type FontWeight,
  LIST_STYLE_TYPES,
  type ListStyleType,
  OVERFLOW_VALUES,
  PAGE_BREAKS,
  type PageBreak,
  POSITIONS,
  type Position,
  type Specificity,
  type StyledNode,
  TEXT_ALIGNMENTS,
  type TextAlignment,
  TEXT_DECORATIONS,
  type TextDecoration,
  TEXT_TRANSFORMS,
  type TextTransform,
  VERTICAL_ALIGNS,
  type VerticalAlign,
  WHITE_SPACES,
  type WhiteSpace,
} from './types';
