export { parseCssDeclarations, parseCssRules, parseFontFaceRules } from './css';
export {
  calculateSpecificity,
  compareSpecificity,
  matchesSelector,
  resolveStyles,
  type SelectorTarget,
} from './cascade';
export {
  DEFAULT_STYLE,
  DISPLAY_VALUES,
  FONT_STYLES,
  FONT_WEIGHTS,
  getTagStyle,
  POSITIONS,
  TEXT_ALIGNMENTS,
  TEXT_DECORATIONS,
  type ComputedStyle,
  type CssRule,
  type Display,
  type FontFaceRule,
  type FontStyle,
  type FontWeight,
  type Position,
  type Specificity,
  type StyledNode,
  type TextAlignment,
  type TextDecoration,
  type VerticalAlign,
  VERTICAL_ALIGNS,
} from './core';
