import 'dart:io';

import 'package:hooks/hooks.dart';

import 'target.dart';

typedef RitoPathExists = bool Function(String path);

/// Resolves Cargo without assuming that an IDE inherited the user's shell.
String ritoCargoExecutable({
  Map<String, String>? platformEnvironment,
  RitoPathExists? pathExists,
  String? pathSeparator,
  String? pathListSeparator,
  bool? windows,
}) {
  final environment = platformEnvironment ?? Platform.environment;
  final exists = pathExists ?? (String path) => File(path).existsSync();
  final directorySeparator = pathSeparator ?? Platform.pathSeparator;
  final listSeparator = pathListSeparator ?? (Platform.isWindows ? ';' : ':');
  final isWindows = windows ?? Platform.isWindows;
  final pathDirectories =
      environment['PATH']
          ?.split(listSeparator)
          .where((path) => path.isNotEmpty)
          .toList(growable: false) ??
      const <String>[];

  final explicit = environment['CARGO'];
  if (explicit != null && explicit.isNotEmpty) {
    final resolved = _resolveExecutable(
      explicit,
      pathDirectories: pathDirectories,
      exists: exists,
      pathSeparator: directorySeparator,
      windows: isWindows,
    );
    if (resolved != null) {
      return resolved;
    }
  }

  final fromPath = _findOnPath(
    'cargo',
    pathDirectories: pathDirectories,
    exists: exists,
    pathSeparator: directorySeparator,
    windows: isWindows,
  );
  if (fromPath != null) {
    return fromPath;
  }

  final home = environment['HOME'] ?? environment['USERPROFILE'];
  if (home != null && home.isNotEmpty) {
    for (final name in _executableNames('cargo', windows: isWindows)) {
      final candidate = _joinPath(<String>[
        home,
        '.cargo',
        'bin',
        name,
      ], directorySeparator);
      if (exists(candidate)) {
        return candidate;
      }
    }
  }
  throw InfraError(
    message:
        'Cargo was not found via CARGO, PATH, or ~/.cargo/bin. Install '
        'the repository-pinned Rust toolchain without running it from the hook.',
  );
}

String? _resolveExecutable(
  String command, {
  required List<String> pathDirectories,
  required RitoPathExists exists,
  required String pathSeparator,
  required bool windows,
}) {
  if (exists(command)) {
    return command;
  }
  if (command.contains('/') || command.contains('\\')) {
    return null;
  }
  return _findOnPath(
    command,
    pathDirectories: pathDirectories,
    exists: exists,
    pathSeparator: pathSeparator,
    windows: windows,
  );
}

String? _findOnPath(
  String command, {
  required List<String> pathDirectories,
  required RitoPathExists exists,
  required String pathSeparator,
  required bool windows,
}) {
  for (final directory in pathDirectories) {
    for (final name in _executableNames(command, windows: windows)) {
      final candidate = _joinPath(<String>[directory, name], pathSeparator);
      if (exists(candidate)) {
        return candidate;
      }
    }
  }
  return null;
}

List<String> _executableNames(String command, {required bool windows}) {
  if (!windows || command.contains('.')) {
    return <String>[command];
  }
  return <String>['$command.exe', '$command.cmd', '$command.bat', command];
}

String _joinPath(List<String> parts, String separator) {
  return parts
      .map((part) {
        if (part.endsWith('/') || part.endsWith('\\')) {
          return part.substring(0, part.length - 1);
        }
        return part;
      })
      .join(separator);
}

final class RitoWorkspace {
  const RitoWorkspace(this.root);

  /// Picks the Rust workspace to compile.
  ///
  /// In a repository checkout the live crates win, even when a
  /// `native/` snapshot is lying around. That snapshot is generated by
  /// `scripts/prepare-flutter-release.mjs` for publishing and is
  /// gitignored, so it does not move when the crates do: preferring it
  /// silently compiles yesterday's engine against today's Dart, and the
  /// first thing that breaks is a wire mismatch that reads like a
  /// protocol bug rather than a stale build.
  ///
  /// A published package has no repository above it, so it falls back
  /// to the bundled snapshot — which is the only source it has.
  factory RitoWorkspace.fromPackageRoot(
    Uri packageRoot, {
    RitoPathExists? pathExists,
  }) {
    final exists = pathExists ?? (String path) => File(path).existsSync();
    final repositoryRoot = packageRoot.resolve('../../');
    if (exists(repositoryRoot.resolve('crates/rito-core/Cargo.toml').toFilePath())) {
      return RitoWorkspace(repositoryRoot);
    }
    final packagedRoot = packageRoot.resolve('native/');
    if (exists(packagedRoot.resolve('Cargo.toml').toFilePath())) {
      return RitoWorkspace(packagedRoot);
    }
    return RitoWorkspace(repositoryRoot);
  }

  final Uri root;

  Uri get manifest => root.resolve('Cargo.toml');
  Uri get lockfile => root.resolve('Cargo.lock');
  Uri get toolchain => root.resolve('rust-toolchain.toml');
  Uri get crates => root.resolve('crates/');
  Uri get ffiManifest => root.resolve('crates/rito-ffi/Cargo.toml');

  List<Uri> get hookDependencies => <Uri>[
    manifest,
    lockfile,
    toolchain,
    crates,
  ];

  void validate() {
    for (final file in <Uri>[manifest, lockfile, toolchain, ffiManifest]) {
      if (!File.fromUri(file).existsSync()) {
        throw BuildError(
          message: 'rito_flutter expected a Rito workspace file at $file.',
        );
      }
    }
    if (!Directory.fromUri(crates).existsSync()) {
      throw BuildError(message: 'Rito workspace crates directory is missing.');
    }
  }
}

final class RitoCargoBuildPlan {
  RitoCargoBuildPlan({
    required this.workspace,
    required Uri outputDirectory,
    required this.target,
    Map<String, String> toolchainEnvironment = const <String, String>{},
  }) : cargoTargetDirectory = outputDirectory.resolve('cargo-target/'),
       arguments = <String>[
         'build',
         '--release',
         '--locked',
         '--jobs',
         '1',
         '--package',
         'rito-ffi',
         ...target.cargoTargetArguments,
       ],
       environment = <String, String>{
         ...toolchainEnvironment,
         'CARGO_TARGET_DIR': outputDirectory
             .resolve('cargo-target/')
             .toFilePath(),
         'CARGO_BUILD_JOBS': '1',
         'CARGO_INCREMENTAL': '0',
         'CARGO_PROFILE_RELEASE_PANIC': 'unwind',
       };

  final RitoWorkspace workspace;
  final RitoCargoTarget target;
  final Uri cargoTargetDirectory;
  final List<String> arguments;
  final Map<String, String> environment;

  Uri get expectedLibrary => target.libraryUnder(cargoTargetDirectory);
}

final class RitoCargoBuilder {
  const RitoCargoBuilder();

  Future<Uri> build(RitoCargoBuildPlan plan) async {
    Directory.fromUri(plan.cargoTargetDirectory).createSync(recursive: true);
    final cargo = ritoCargoExecutable();
    final Process process;
    try {
      process = await Process.start(
        cargo,
        plan.arguments,
        workingDirectory: plan.workspace.root.toFilePath(),
        environment: plan.environment,
        includeParentEnvironment: true,
        runInShell: Platform.isWindows,
      );
    } on ProcessException catch (error, stackTrace) {
      throw InfraError(
        message: 'Unable to start the pinned Rito Cargo build.',
        wrappedException: error,
        wrappedTrace: stackTrace,
      );
    }

    final stdoutDone = stdout.addStream(process.stdout);
    final stderrDone = stderr.addStream(process.stderr);
    final processExitCode = await process.exitCode;
    await stdoutDone;
    await stderrDone;
    if (processExitCode != 0) {
      throw BuildError(
        message:
            'cargo ${plan.arguments.join(' ')} failed with exit code '
            '$processExitCode.',
      );
    }

    final library = File.fromUri(plan.expectedLibrary);
    if (!library.existsSync()) {
      throw BuildError(
        message: 'Cargo succeeded but did not produce ${library.path}.',
      );
    }
    return library.absolute.uri;
  }
}
