// Pixel-diffs the two pens' renders of the paint-parity corpus and
// writes out/report.md sorted by mismatch count, plus a red-overlay
// diff PNG per divergent fixture. The report on disk is the verdict.
//
//   node tools/paint-parity/diff.mjs [outRoot]
import { createRequire } from 'node:module';
import { mkdirSync, readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const REPO = new URL('../..', import.meta.url).pathname;
const HERE = new URL('.', import.meta.url).pathname;
const { PNG } = createRequire(`${REPO}package.json`)('pngjs');

const outRoot = process.argv[2] ?? path.join(HERE, 'out');
const browserDir = path.join(outRoot, 'browser');
const flutterDir = path.join(outRoot, 'flutter');
const diffDir = path.join(outRoot, 'diff');
mkdirSync(diffDir, { recursive: true });

const names = readdirSync(browserDir)
  .filter((f) => f.endsWith('.png'))
  .map((f) => f.slice(0, -4))
  .sort();

const results = [];
for (const name of names) {
  const flutterPath = path.join(flutterDir, `${name}.png`);
  if (!existsSync(flutterPath)) {
    results.push({ name, error: 'missing flutter render' });
    continue;
  }
  const a = PNG.sync.read(readFileSync(path.join(browserDir, `${name}.png`)));
  const b = PNG.sync.read(readFileSync(flutterPath));
  if (a.width !== b.width || a.height !== b.height) {
    results.push({ name, error: `size ${a.width}x${a.height} vs ${b.width}x${b.height}` });
    continue;
  }
  const total = a.width * a.height;
  let diffCount = 0;
  let maxDelta = 0;
  let sumDelta = 0;
  const out = new PNG({ width: a.width, height: a.height });
  for (let i = 0; i < total * 4; i += 4) {
    let pixelDelta = 0;
    for (let c = 0; c < 4; c += 1) {
      pixelDelta = Math.max(pixelDelta, Math.abs(a.data[i + c] - b.data[i + c]));
    }
    if (pixelDelta > 0) {
      diffCount += 1;
      maxDelta = Math.max(maxDelta, pixelDelta);
      sumDelta += pixelDelta;
      out.data[i] = 255;
      out.data[i + 1] = 0;
      out.data[i + 2] = 0;
      out.data[i + 3] = 255;
    } else {
      // Faded browser render as context under the red overlay.
      out.data[i] = 192 + (a.data[i] >> 2);
      out.data[i + 1] = 192 + (a.data[i + 1] >> 2);
      out.data[i + 2] = 192 + (a.data[i + 2] >> 2);
      out.data[i + 3] = 255;
    }
  }
  if (diffCount > 0) {
    writeFileSync(path.join(diffDir, `${name}.png`), PNG.sync.write(out));
  }
  results.push({
    name,
    diffCount,
    total,
    ratio: diffCount / total,
    maxDelta,
    meanDelta: diffCount === 0 ? 0 : sumDelta / diffCount,
  });
}

results.sort((x, y) => (y.diffCount ?? Infinity) - (x.diffCount ?? Infinity));

const lines = [
  '# paint-parity diff report',
  '',
  `- corpus: ${names.length} fixtures`,
  `- generated by tools/paint-parity/diff.mjs`,
  '',
  '| fixture | diff px | ratio | max Δ | mean Δ |',
  '|---|---|---|---|---|',
];
for (const r of results) {
  if (r.error) {
    lines.push(`| ${r.name} | ERROR: ${r.error} | | | |`);
  } else {
    lines.push(
      `| ${r.name} | ${r.diffCount}/${r.total} | ${(r.ratio * 100).toFixed(3)}% | ${r.maxDelta} | ${r.meanDelta.toFixed(1)} |`,
    );
  }
}
lines.push('');
writeFileSync(path.join(outRoot, 'report.md'), lines.join('\n'));
console.log(lines.join('\n'));
